name: 'CodeTour Watch'
description: 'Flags file changes that may affect CodeTour content'
author: 'Philippe Ozil <@pozil> and contributors'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN, needed to comment the PR.'
        required: false
        default: ${{ github.token }}
    silent:
        description: 'Optional flag that turns off the comment on the PR.'
        required: false
        default: 'false'
    tour-path:
        description: 'Optional flag that specifies a custom `.tour` folder location.'
        required: false
        default: '.tours/'
outputs:
    commentInfoJson:
        description: 'A JSON string of the comment create/update request body (or `"null"` if no code tours are affected), in case you need to make the request in a separate workflow.'
    impactedFiles:
        description: 'The list of files covered by tours that were changed.'
    impactedTours:
        description: 'The list of tours that were impacted by the PR.'
    missingTourUpdates:
        description: 'The list of tours that were impacted by the changes but that are not part of the PR.'

runs:
    using: 'node12'
    main: 'src/index.js'

branding:
    icon: 'book'
    color: 'yellow'
