name: 'CodeTour Watch'
description: 'Flags file changes that may affect CodeTour content'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN, needed to comment the PR.'
        required: false
        default: ${{ github.token }}
    silent:
        description: 'Optional flag that turns off the comment on the PR.'
        required: false
        default: 'false'
    tour-path:
        description: 'Optional flag that specifies a custom `.tour` folder location.'
        required: false
        default: '.tours/'

runs:
    using: 'node12'
    main: 'src/index.js'

branding:
    icon: 'book'
    color: 'yellow'
